version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    restart: always
    tty: true
    stdin_open: true
    command: "bash entrypoint.sh"
